### ISSUE TITLE
debug undefineds

### ISSUE THREAD

**Issue by amundo** [chirila/kullilli#7]
There are a bunch showing up in the interface.

E.g., 

yalagubanu ini yanhtha

**Comment by amundo** [comment]
139 of them 😑

**Comment by chirila** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kullilli site](https://trello.com/c/SmYlM7Ig/44-kullilli-site)

**Comment by chirila** [comment]
assuming this was because word gloss wasn't entered?
